"use strict";

export const selectorsList = [
  {
    id: 1,
    list: ["Home", "House"],
    key: "main",
  },
  {
    id: 20,
    title: "Home",
    list: ["Tehran", "Mazandaran"],
    key: "second",
  },
  {
    id: 21,
    title: "House",
    list: ["Mashad", "Kerman"],
    key: "second",
  },
  {
    id: 30,
    title: "Tehran",
    list: ["Buy1", "Rent1"],
    key: "third",
  },
  {
    id: 31,
    title: "Mazandaran",
    list: ["Buy2", "Rent2"],
    key: "third",
  },
  {
    id: 32,
    title: "Mashad",
    list: ["Buy3", "Rent3"],
    key: "third",
  },
  {
    id: 33,
    title: "Kerman",
    list: ["Buy4", "Rent4"],
    key: "third",
  },
];

export const attributes = [
  {
    title: "Buy1",
    list: [
      {
        type: "type",
        list: ["white", "black"],
      },
      {
        type: "type1",
        list: ["white2", "black2"],
      },
      {
        type: "type2",
        list: ["white3", "black3"],
      },
    ],
  },
  {
    title: "Buy2",
    list: [
      {
        type: "type",
        list: ["red", "green"],
      },
      {
        type: "type1",
        list: ["red2", "green2"],
      },
      {
        type: "type2",
        list: ["red3", "green3"],
      },
    ],
  },
  {
    title: "Buy3",
    list: [
      {
        type: "type",
        list: ["yellow", "orange"],
      },
      {
        type: "type1",
        list: ["yellow2", "orange2"],
      },
      {
        type: "type2",
        list: ["yellow3", "orange3"],
      },
    ],
  },
  {
    title: "Buy4",
    list: [
      {
        type: "type",
        list: ["pink", "purple"],
      },
      {
        type: "type1",
        list: ["pink2", "purple2"],
      },
      {
        type: "type2",
        list: ["pink3", "purple3"],
      },
    ],
  },
  {
    title: "Rent1",
    list: [
      {
        type: "type",
        list: ["big", "small"],
      },
      {
        type: "type1",
        list: ["big1", "small1"],
      },
      {
        type: "type2",
        list: ["big2", "small2"],
      },
    ],
  },
  {
    title: "Rent2",
    list: [
      {
        type: "type",
        list: ["tiny", "huge"],
      },
      {
        type: "type1",
        list: ["tiny2", "huge2"],
      },
      {
        type: "type2",
        list: ["tiny3", "huge3"],
      },
    ],
  },
  {
    title: "Rent3",
    list: [
      {
        type: "type",
        list: ["hi", "bye"],
      },
      {
        type: "type1",
        list: ["hi2", "bye2"],
      },
      {
        type: "type2",
        list: ["hi3", "bye3"],
      },
    ],
  },
  {
    title: "Rent4",
    list: [
      {
        type: "type",
        list: ["come", "go"],
      },
      {
        type: "type1",
        list: ["come2", "go2"],
      },
      {
        type: "type2",
        list: ["come3", "go3"],
      },
    ],
  },
];

export const itemsList = [
  {
    id: 1,
    title: "House Tehran 1",
    src: "/images/01.png",
    location: "Shahrak Gharb",
    price: "100,000,000,000",
    situation: "Buy1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 2,
    title: "Home Tehran 1",
    src: "/images/02.png",
    location: "Farmanie",
    price: "110,000,000,000",
    situation: "Rent1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 3,
    title: "Home Tehran 2",
    src: "/images/03.png",
    location: "Gisha",
    price: "12,000,000,000",
    situation: "Rent2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 4,
    title: "House Mazandaran 1",
    src: "/images/04.png",
    location: "Noor",
    price: "5,000,000,000",
    situation: "Buy2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 5,
    title: "House Mazandaran 2",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 6,
    title: "Home Mazandaran 1",
    src: "/images/06.png",
    location: "Amol",
    price: "2,000,000,000",
    situation: "Rent3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 7,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 8,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Rent4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 1,
    title: "House Tehran 1",
    src: "/images/01.png",
    location: "Shahrak Gharb",
    price: "100,000,000,000",
    situation: "Buy1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 2,
    title: "Home Tehran 1",
    src: "/images/02.png",
    location: "Farmanie",
    price: "110,000,000,000",
    situation: "Rent1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 3,
    title: "Home Tehran 2",
    src: "/images/03.png",
    location: "Gisha",
    price: "12,000,000,000",
    situation: "Rent2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 4,
    title: "House Mazandaran 1",
    src: "/images/04.png",
    location: "Noor",
    price: "5,000,000,000",
    situation: "Buy2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 5,
    title: "House Mazandaran 2",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 6,
    title: "Home Mazandaran 1",
    src: "/images/06.png",
    location: "Amol",
    price: "2,000,000,000",
    situation: "Rent3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 7,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 8,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Rent4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 1,
    title: "House Tehran 1",
    src: "/images/01.png",
    location: "Shahrak Gharb",
    price: "100,000,000,000",
    situation: "Buy1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 2,
    title: "Home Tehran 1",
    src: "/images/02.png",
    location: "Farmanie",
    price: "110,000,000,000",
    situation: "Rent1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 3,
    title: "Home Tehran 2",
    src: "/images/03.png",
    location: "Gisha",
    price: "12,000,000,000",
    situation: "Rent2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 4,
    title: "House Mazandaran 1",
    src: "/images/04.png",
    location: "Noor",
    price: "5,000,000,000",
    situation: "Buy2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 5,
    title: "House Mazandaran 2",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 6,
    title: "Home Mazandaran 1",
    src: "/images/06.png",
    location: "Amol",
    price: "2,000,000,000",
    situation: "Rent3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 7,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 8,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Rent4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 1,
    title: "House Tehran 1",
    src: "/images/01.png",
    location: "Shahrak Gharb",
    price: "100,000,000,000",
    situation: "Buy1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 2,
    title: "Home Tehran 1",
    src: "/images/02.png",
    location: "Farmanie",
    price: "110,000,000,000",
    situation: "Rent1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 3,
    title: "Home Tehran 2",
    src: "/images/03.png",
    location: "Gisha",
    price: "12,000,000,000",
    situation: "Rent2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 4,
    title: "House Mazandaran 1",
    src: "/images/04.png",
    location: "Noor",
    price: "5,000,000,000",
    situation: "Buy2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 5,
    title: "House Mazandaran 2",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 6,
    title: "Home Mazandaran 1",
    src: "/images/06.png",
    location: "Amol",
    price: "2,000,000,000",
    situation: "Rent3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 7,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 8,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Rent4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 1,
    title: "House Tehran 1",
    src: "/images/01.png",
    location: "Shahrak Gharb",
    price: "100,000,000,000",
    situation: "Buy1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 2,
    title: "Home Tehran 1",
    src: "/images/02.png",
    location: "Farmanie",
    price: "110,000,000,000",
    situation: "Rent1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 3,
    title: "Home Tehran 2",
    src: "/images/03.png",
    location: "Gisha",
    price: "12,000,000,000",
    situation: "Rent2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 4,
    title: "House Mazandaran 1",
    src: "/images/04.png",
    location: "Noor",
    price: "5,000,000,000",
    situation: "Buy2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 5,
    title: "House Mazandaran 2",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 6,
    title: "Home Mazandaran 1",
    src: "/images/06.png",
    location: "Amol",
    price: "2,000,000,000",
    situation: "Rent3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 7,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 8,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Rent4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 1,
    title: "House Tehran 1",
    src: "/images/01.png",
    location: "Shahrak Gharb",
    price: "100,000,000,000",
    situation: "Buy1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 2,
    title: "Home Tehran 1",
    src: "/images/02.png",
    location: "Farmanie",
    price: "110,000,000,000",
    situation: "Rent1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 3,
    title: "Home Tehran 2",
    src: "/images/03.png",
    location: "Gisha",
    price: "12,000,000,000",
    situation: "Rent2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 4,
    title: "House Mazandaran 1",
    src: "/images/04.png",
    location: "Noor",
    price: "5,000,000,000",
    situation: "Buy2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 5,
    title: "House Mazandaran 2",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 6,
    title: "Home Mazandaran 1",
    src: "/images/06.png",
    location: "Amol",
    price: "2,000,000,000",
    situation: "Rent3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 7,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 8,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Rent4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 1,
    title: "House Tehran 1",
    src: "/images/01.png",
    location: "Shahrak Gharb",
    price: "100,000,000,000",
    situation: "Buy1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 2,
    title: "Home Tehran 1",
    src: "/images/02.png",
    location: "Farmanie",
    price: "110,000,000,000",
    situation: "Rent1",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 3,
    title: "Home Tehran 2",
    src: "/images/03.png",
    location: "Gisha",
    price: "12,000,000,000",
    situation: "Rent2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 4,
    title: "House Mazandaran 1",
    src: "/images/04.png",
    location: "Noor",
    price: "5,000,000,000",
    situation: "Buy2",
    province: "Mazandaran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 5,
    title: "House Mazandaran 2",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 6,
    title: "Home Mazandaran 1",
    src: "/images/06.png",
    location: "Amol",
    price: "2,000,000,000",
    situation: "Rent3",
    province: "Mashad",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 7,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 8,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Rent4",
    province: "Kerman",
    type: "House",
    attribute: "Pool",
  },
];

export const images = [
  {
    province: "Tehran",
    type: "Home",
    situation: "Buy1",
    src: "/images/03.png",
  },
  {
    province: "Tehran",
    type: "Home",
    situation: "Rent1",
    src: "/images/04.png",
  },
  {
    province: "Mazandaran",
    type: "Home",
    situation: "Buy2",
    src: "/images/02.png",
  },
  {
    province: "Mazandaran",
    type: "Home",
    situation: "Rent2",
    src: "/images/01.png",
  },
  {
    province: "Mashad",
    type: "House",
    situation: "Rent3",
    src: "/images/02.png",
  },
  {
    province: "Mashad",
    type: "House",
    situation: "Buy3",
    src: "/images/05.png",
  },
  {
    province: "Kerman",
    type: "House",
    situation: "Buy4",
    src: "/images/01.png",
  },
  {
    province: "Kerman",
    type: "House",
    situation: "Rent4",
    src: "/images/06.png",
  },
];
