"use strict";

export const selectorsList = [
  {
    id: 1,
    list: ["Home", "House"],
    key: "main",
  },
  {
    id: 2,
    list: ["Tehran", "Mazandaran"],
    key: "second",
  },
  {
    id: 3,
    list: ["Buy", "Rent"],
    key: "third",
  },
  {
    id: 4,
    list: ["Pool", "Yard"],
    key: "first",
  },
];

export const itemsList = [
  {
    id: 1,
    title: "House Tehran 1",
    src: "/images/01.png",
    location: "Shahrak Gharb",
    price: "100,000,000,000",
    situation: "Buy",
    province: "Tehran",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 2,
    title: "Home Tehran 1",
    src: "/images/02.png",
    location: "Farmanie",
    price: "110,000,000,000",
    situation: "Rent",
    province: "Tehran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 3,
    title: "Home Tehran 2",
    src: "/images/03.png",
    location: "Gisha",
    price: "12,000,000,000",
    situation: "Rent",
    province: "Tehran",
    type: "Home",
    attribute: "Pool",
  },
  {
    id: 4,
    title: "House Mazandaran 1",
    src: "/images/04.png",
    location: "Noor",
    price: "5,000,000,000",
    situation: "Buy",
    province: "Mazandaran",
    type: "House",
    attribute: "Pool",
  },
  {
    id: 5,
    title: "House Mazandaran 2",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy",
    province: "Mazandaran",
    type: "House",
    attribute: "Yard",
  },
  {
    id: 6,
    title: "Home Mazandaran 1",
    src: "/images/06.png",
    location: "Amol",
    price: "2,000,000,000",
    situation: "Rent",
    province: "Mazandaran",
    type: "Home",
    attribute: "Yard",
  },
  {
    id: 5,
    title: "House Mazandaran 3",
    src: "/images/05.png",
    location: "Babol",
    price: "4,000,000,000",
    situation: "Buy",
    province: "Mazandaran",
    type: "House",
    attribute: "Pool",
  },
];

export const images = [
  {
    province: "Tehran",
    type: "House",
    situation: "Buy",
    src: "/images/01.png",
  },
  {
    province: "Tehran",
    type: "House",
    situation: "Rent",
    src: "/images/02.png",
  },
  {
    province: "Tehran",
    type: "Home",
    situation: "Buy",
    src: "/images/03.png",
  },
  {
    province: "Tehran",
    type: "Home",
    situation: "Rent",
    src: "/images/04.png",
  },
  {
    province: "Mazandaran",
    type: "House",
    situation: "Buy",
    src: "/images/05.png",
  },
  {
    province: "Mazandaran",
    type: "House",
    situation: "Rent",
    src: "/images/06.png",
  },
  {
    province: "Mazandaran",
    type: "Home",
    situation: "Buy",
    src: "/images/02.png",
  },
  {
    province: "Mazandaran",
    type: "Home",
    situation: "Rent",
    src: "/images/01.png",
  },
];
